apiVersion: apps/v1
kind: Deployment
metadata:
    name: spaceryder
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: spaceryder
    template:
        metadata:
            labels:
                app: spaceryder
        spec:
            containers:
                - name: spaceryder
                  image: spaceryder_be:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  env:
                      - name: NODE_ENV
                        value: 'development'
                      - name: PORT
                        value: '3000'
                      - name: DB_HOST
                        value: 'postgres-service'
                      - name: DB_PORT
                        value: '5432'
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: spaceryder-secret
                                key: POSTGRES_USER
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: spaceryder-secret
                                key: POSTGRES_PASSWORD
                      - name: DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: spaceryder-secret
                                key: POSTGRES_DB
                      - name: REDIS_HOST
                        value: 'redis-service'
                      - name: REDIS_PORT
                        value: '6379'
                  resources:
                      limits:
                          cpu: '500m'
                          memory: '512Mi'
                      requests:
                          cpu: '200m'
                          memory: '256Mi'
