apiVersion: v1
kind: ConfigMap
metadata:
    name: spaceryder-config
    namespace: default
data:
    NODE_ENV: production
    PORT: '3000'
    POSTGRES_HOST: postgres-service
    REDIS_HOST: redis-service
